language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"

services:
  - mongodb

before_script:
  - yarn install

script:
  - yarn test
env:
  - DATABASE_URL=mongodb://localhost:27017/node-express-mongodb-server

